# Generated by Django 4.2.29 on 2026-03-13 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název díla')),
                ('rok_vydani', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rok prvního vydání')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Stručný obsah či význam díla')),
            ],
            options={
                'verbose_name': 'Dílo',
                'verbose_name_plural': 'Díla',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Epocha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název epochy')),
                ('obdobi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Časové vymezení (např. 5. stol. př. n. l.)')),
                ('charakteristika', models.TextField(verbose_name='Základní charakteristika a duch doby')),
            ],
            options={
                'verbose_name': 'Epocha',
                'verbose_name_plural': 'Epochy',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Smer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název směru')),
                ('definice', models.TextField(verbose_name='Definice a hlavní principy')),
            ],
            options={
                'verbose_name': 'Myšlenkový směr',
                'verbose_name_plural': 'Myšlenkové směry',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Myslitel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=150, verbose_name='Jméno myslitele')),
                ('roky_zivota', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roky života (např. 1844–1900)')),
                ('zivotopis', models.TextField(verbose_name='Životopis a intelektuální vývoj')),
                ('epocha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='myslitele', to='app.epocha', verbose_name='Historická epocha')),
                ('smery', models.ManyToManyField(blank=True, related_name='myslitele', to='app.smer', verbose_name='Myšlenkové směry')),
            ],
            options={
                'verbose_name': 'Myslitel',
                'verbose_name_plural': 'Myslitelé',
                'ordering': ['jmeno'],
            },
        ),
        migrations.CreateModel(
            name='Myslenka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Znění myšlenky či citátu')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myslenky', to='app.myslitel', verbose_name='Autor myšlenky')),
                ('dilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myslenky', to='app.dilo', verbose_name='Zdrojové dílo')),
                ('ulozili_uzivatele', models.ManyToManyField(blank=True, related_name='ulozene_myslenky', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelé, kteří si uložili')),
            ],
            options={
                'verbose_name': 'Myšlenka',
                'verbose_name_plural': 'Myšlenky',
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text komentáře')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True, verbose_name='Čas vytvoření')),
                ('dilo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='app.dilo')),
                ('myslenka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='app.myslenka')),
                ('myslitel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='app.myslitel')),
                ('smer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to='app.smer')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentare', to=settings.AUTH_USER_MODEL, verbose_name='Autor komentáře')),
            ],
            options={
                'verbose_name': 'Komentář',
                'verbose_name_plural': 'Komentáře',
                'ordering': ['-vytvoreno'],
            },
        ),
        migrations.AddField(
            model_name='dilo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dila', to='app.myslitel', verbose_name='Autor díla'),
        ),
    ]
